/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef TEACHERANDLOGIN_PRIVATE_H
#define TEACHERANDLOGIN_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.2.0.0"
#define VER_MAJOR	1
#define VER_MINOR	2
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	""
#define FILE_VERSION	"1.2.0.0"
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"1.2.0.0"

#endif /*TEACHERANDLOGIN_PRIVATE_H*/
